---
instance:
  port: 3128
  username: user
  password: pass
  scaling:
    min: 1
    max: 5
    downscaleDelay: 60
  checkAliveDelay: 100
  stopIfCrashedDelay: 100
  autorestart:
    minDelay: 100
    maxDelay: 500

logs:
  path: "/Users/contactone/Desktop/scroxy.log"

providers:
  - type: digitalocean
    token: "$(DIGITALOCEAN_TOKEN)"
    region: "ams3"
    sshKeyNames:
      - "Digital Ocean"
    size: "s-1vcpu-512mb-10gb"
    name: "ScroxyEndpoint"
    imageName: "Squid worker"
    projectName: "Squid"
    tags:
      - scroxy
    max: 5

proxy:
  port: 3128
  squid:
    path: "/opt/homebrew/opt/squid/sbin/squid"
  auth:
    path: "/opt/homebrew/Cellar/squid/5.9/libexec/basic_ncsa_auth"
    username: "username"
    password: "password"
  mitm:
    cert_filename: null
    key_filename: null